# Use uma imagem base oficial do PHP com FPM no Alpine
FROM php:8.2-fpm-alpine

# Instale dependências do sistema e de compilação
RUN apk --no-cache add \
    freetype-dev \
    libjpeg-turbo-dev \
    libpng-dev \
    libzip-dev \
    oniguruma-dev \
    git \
    curl \
    bash \
    autoconf \
    make \
    gcc \
    g++ \
    linux-headers

# Instale extensões do PHP necessárias
RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install mysqli pdo pdo_mysql mbstring exif pcntl bcmath gd zip

# Instale e configure o Xdebug
RUN pecl install xdebug && docker-php-ext-enable xdebug

# Instale o Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Defina o diretório de trabalho
WORKDIR /var/www/html/cadastro_de_clientes

# Instalação do Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
ENV COMPOSER_ALLOW_SUPERUSER=1

# Copiando arquivo
COPY ./php.ini /usr/local/etc/php/php.ini
COPY . /var/www/html/cadastro_de_clientes

# Ajusta as permissões do diretório
RUN chown -R www-data:www-data /var/www/html/cadastro_de_clientes

# Exponha a porta 9000 para PHP-FPM
EXPOSE 9000

# Definindo o script de inicialização como ponto de entrada
CMD ["php-fpm"]